### ISSUE TITLE
Homepage: falta una imagen en mobile seccion programas

### ISSUE THREAD

**Issue by jleiva** [cetav-ddw/cegea#19]
Usando el emulador de chrome una imagen esta fallando

![image](https://user-images.githubusercontent.com/598867/68358310-c7ea1280-00dd-11ea-8ec8-28c281d31012.png)

**Comment by LilMonRod** [comment]
si, porque el nombre de la imagen está mal escrito.
por eso en el pull de home fixes se corrige ese bug.

**Comment by LilMonRod** [comment]
solucionado

**Comment by LilMonRod** [comment]
Solucionado
